export const GET_FOODS_REQUESTED = 'GET_FOODS_REQUESTED';
export const GET_FOODS_SUCCESS = 'GET_FOODS_SUCCESS';
export const GET_FOODS_FAILED = 'GET_FOODS_FAILED';


export const GET_FOODDETAILS_REQUESTED = 'GET_FOODDETAILS_REQUESTED';
export const GET_FOODDETAILS_SUCCESS = 'GET_FOODDETAILS_SUCCESS';
export const GET_FOODDETAILS_FAILED = 'GET_FOODDETAILS_FAILED';